
public interface ValidationMesseges {
	String LOGIN_VALIDATION_EXCEPTION = "LOGIN ALREADY EXIST!";
	String EMAIL_VALIDATION_EXCEPTION = "EMAIL_VALIDATION_EXCEPTION";
	String CONFIRM_EMAIL_EXCEPTION = "CONFIRM_EMAIL_EXCEPTION";
}
